###############################################################################
#                             APPLICATION CONFIG                              #
###############################################################################

# Development options
# debug: true

spring:
  # AOP
  aop:
    proxy-target-class: false

# Audit
management:
  endpoints:
    web:
      exposure:
        include: auditevents
    enabled-by-default: false
    auditevents:
      enabled: true